### ISSUE TITLE
entity not found

### ISSUE THREAD

**Issue by polarathene** [mitnk/cicada#11]
Trying out this simple script for timing operation. Is the `entity not found` lines a bug? They seem similar to https://github.com/mitnk/cicada/issues/9 with `exit`.

```
time ./cicada -c 'for i in $(seq 1 1000000);do [ 1 = 1 ];done'
for: entity not found
do: entity not found
done: entity not found

real    0m0.172s
user    0m0.129s
sys     0m0.050s
```

Here is the equivalent for dash:

```
$ time dash -c 'for i in $(seq 1 1000000);do [ 1 = 1 ];done'

real    0m0.748s
user    0m0.708s
sys     0m0.021s
```

**Comment by mitnk** [comment]
Hi polarathene, this is not a bug. As said in readme, cicada is a simple shell, not intending to implement stuff like functions or script programing ability.
