### ISSUE TITLE
Vi mode?

### ISSUE THREAD

**Issue by thornjad** [mitnk/cicada#17]
Is there any interest in adding in a Vi mode for editing commands, similar to what `set -o vi` does in Bash? I find this mode very useful compared to using arrow keys.

**Comment by mitnk** [comment]
For the input reading/editing part, cicada depends on an upstream [linefeed](https://github.com/murarth/linefeed) lib. Currently it seems not support VI mode yet.

**Comment by thornjad** [comment]
Interesting, thank you! I might look at linefeed; I'll comment here or reopen this issue if anything happens!
