### ISSUE TITLE
cicada seems to have trouble with certain bash function names

### ISSUE THREAD

**Issue by MSF-Jarvis** [mitnk/cicada#21]
Case in point being git's completion [script](https://github.com/git/git/blob/master/contrib/completion/git-prompt.sh), trying to run `source ~/.git-prompt.sh` from inside `cicada` throws with `cicada: __git_ps1_show_upstream: command not found`.

So far I have tried the following things:

- Drop the leading underscores in function names: No change
- Add the `function` keyword before function names: No change
- Mark `~/.git-prompt.sh` as executable, add a `bash` shebang and directly execute it using `~/.git-prompt.sh`: Execution succeeds but that doesn't resolve our use-case of needing those functions in the current shell.

I'll be glad to follow up with any additional debugging you'd like me to do.

**Comment by mitnk** [comment]
Hi @MSF-Jarvis, seems you thought cicada is compatible with bash/zsh - it's not. Please see FAQ section in the README. Also you could check out how completions works in cicada in docs as well.

**Comment by MSF-Jarvis** [comment]
> Hi @MSF-Jarvis, seems you thought cicada is compatible with bash/zsh - it's not. Means you cannot use existing bash/zsh scripts in cicada. You have to re-config stuff in cicada in a new way :-(
> 
> Please see FAQ section in the README. Also you could check out how completions works in cicada in docs as well.

Ah I see, must have misread something along the way. Thanks for the prompt response!
