### ISSUE TITLE
Use as a library

### ISSUE THREAD

**Issue by flying-sheep** [mitnk/cicada#3]
It would be useful to provide functions to

1. Parse input and return if it's complete and chunk it into individual command units (so e.g. a single command execution on its own line or an if statement are both individual command units)
2. Execute code and capture output

The idea is that we can then use it e.g. to power a Jupyter kernel or other alternative interfaces

**Comment by mitnk** [comment]
This is a good suggestion. I will try extract stuff out into a lib, or make cicada both a bin and a lib. Thanks @flying-sheep

**Comment by mitnk** [comment]
Starting from v0.7.1, cicada also a library. Please checkout [https://docs.rs/cicada/0.7.1/cicada/](https://docs.rs/cicada/0.7.1/cicada/) for details.

**Comment by flying-sheep** [comment]
awesome!

**Comment by hugo-aa** [comment]
1. cicada currently doesn't support multiple line commands. So `foo\nbar` breaks.

2. since `foo;bar` are multiple commands, so you should use `line_to_cmds()` first. But maybe I need to rename `line_to_tokens` to `cmd_to_tokens`.

**Comment by flying-sheep** [comment]
> cicada currently doesn't support multiple line commands. So foo\nbar breaks.

aah, i see.

so once it does, it probably gains a `script_to_cmds` function or something.

**Comment by mitnk** [comment]
Since linefeed, which cicada depends on doesn't support multiple line, so cicada won't support it either yet.

For other inputs, I just created #6 for tracking.

**Comment by flying-sheep** [comment]
well, the reason i asked for a library API is that i’d like to write a jupyter kernel in rust, and as a test target, use cicada.

jupyter supports notebooks and a multiline input powered by [prompt toolkit](https://github.com/jonathanslenders/python-prompt-toolkit#readme)

**Comment by mitnk** [comment]
Because cicada even doesn't support functions, multiple line commands are not very useful to support. Which multiple-line command would you like to run?

Is replacing `\n`s to Spaces and then pass to cicada lib an option to you?

**Comment by flying-sheep** [comment]
well, it would have to be part of tokenization. if the `\n` is part of a string, it needs to stay there verbatim, and if it’s after a finished command, it ends that command like a `\n`.

i think long pipes are an useful case for multiline commands, or things like

```bash
cmake .. \
    -DCMAKE_FOO_BAR=1 \
    -DCMAKE_OTHER_OPTION=on \
    …
```
