### ISSUE TITLE
Is it aiming to become an actual POSIX-compatible shell?

### ISSUE THREAD

**Issue by vi** [mitnk/cicada#4]
If yes then functions should also be in the todo list instead of won't do.

**Comment by SentToDevNull** [comment]
A similar question would be feature compatibility with respect to other shells. For example, will my {bash,zsh,ksh,sh,csh} scripts work with this shell?

**Comment by mitnk** [comment]
Thanks @vi and @SentToDevNull. I just added a FAQ section in readme. Please check it out.

**Comment by IBPX** [comment]
> ### Why functions support is in won't do list?
>
> I don't think i have interests or energy to add (bash) functions support or (bash) shell scripting ability.

While I realize it would be a lot of work, I'm not sure I understand what bash has to do with it; functions are supported in practically every shell, and are even [part of the POSIX standard](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_09_05) and sh.

> As the above anwsers hints, while cicada is trying to be POSIX, but it will not be a fully POSIX shell. However, If any command pattern is common and cicada is missing, we can add it.

**Comment by vi** [comment]
Is Cicada a building block of an imaginary "Rust all the way down" operating system (kernel in Rust, drivers in Rust, standard library in Rust, system tools in Rust, so `/bin/sh`-compatible shell also in Rust) or just a fancy "login" shell to type commands into, not for scripts?

**Comment by mitnk** [comment]
@vi a simple shell for typing commands into, I guess.

@IBPX not really related to bash, I'll update it a bit.

**Comment by mitnk** [comment]
I've seen too many surprises on "functions will not be supported? (wtf?)" ;) I may need to put it back in todo list.

**Comment by mitnk** [comment]
Closing this issue. Please find FQA section for it here: https://github.com/mitnk/cicada/blob/master/docs/faq.md#will-cicada-be-posix-compatible
