### ISSUE TITLE
[Feature] Auto-complete

### ISSUE THREAD

**Issue by danimesq** [mitnk/cicada#40]
Did you saw this in Nu? Its simply amazing. I have an idea to make our own approach.

**Comment by mitnk** [comment]
Hey @danimesq, could you provide more details on this?

**Comment by danimesq** [comment]
All I have is an inspiration for this idea: nushell's autocomplete

**Comment by mitnk** [comment]
I never tired nushell. cicada does not have auto-completion. We only have [normal completion](https://github.com/mitnk/cicada/blob/3c67f81b9049c9cb9222d89487c80546164d3f46/docs/completion.md).

Cicada is designed to be simple. I don't think I'd add things like auto-competion, which sounds tricky or slow, haha. We love explicit.
