### ISSUE TITLE
[Question] Does it fallback to Bash on some conditions?

### ISSUE THREAD

**Issue by danimesq** [mitnk/cicada#43]

**Comment by mitnk** [comment]
It does not.

Like bash, if anything wrong when start up, you cannot ssh to your sever if it is the default shell.

It won't fallback to other shells during normal use session. We hope cicada is stable and does not crash. I myself is a heavy user of it, I do not experience crash for a long time. Please report if you encounter a crash while using it.

**Comment by danimesq** [comment]
I mean, does it cover all of the Bash's expected features?

And if don't, that would be good if it fallback when something isn't supported yet.

**Comment by mitnk** [comment]
@danimesq Thanks for asking. No, cicada itself does not do fallback in anyway. Human needs to do that. As described in [scripting doc](https://github.com/mitnk/cicada/blob/3c67f81b9049c9cb9222d89487c80546164d3f46/docs/scripting.md), If you need some serious scripting or something it's good to still use `#!/bin/bash` or Python.

Cicada tries to cover common use cases of bash. We surely does not have energy to fully clone bash :)

**Comment by danimesq** [comment]
@mitnk, if you consider adding a Bash fallback, please reopen this issue.

I want to add cicada as @Floflis' default replacement for bash.

**Comment by mitnk** [comment]
As mentioned in the PR, I would not add the fallback feature, which I think we do not need it actually. Thanks for using cicada :)

Floflis looks cool!
