### ISSUE TITLE
[Feature Request]: Full 8 color prompts

### ISSUE THREAD

**Issue by Cyanide-1** [mitnk/cicada#44]
Hello! this project looks nice, been using cicada shell for a while and i like it, however i noticed the prompts seem to lack the full 8 color spectrum which is standard on tty's, i would appreciate if these colors could be added to the shell prompts! thanks!

**Comment by mitnk** [comment]
Hey @Cyanide-1, the current [prompt items](https://github.com/mitnk/cicada/blob/master/docs/prompt.md#available-prompt-items) are just most basic ones, we could definitely extend it. Could you provide more details how it would look like with 8-bit color capacity?

**Comment by Cyanide-1** [comment]
> Hey @Cyanide-1, the current [prompt items](https://github.com/mitnk/cicada/blob/master/docs/prompt.md#available-prompt-items) are just most basic ones, we could definitely extend it. Could you provide more details how it would look like with 8-bit color capacity?

i was imagining adding like the other colors, like magenta, cyan, and yellow

**Comment by mitnk** [comment]
Addressed in laster master. Please see details in https://github.com/mitnk/cicada/blob/master/docs/prompt.md

**Comment by Cyanide-1** [comment]
sounds cool, thanks!
