### ISSUE TITLE
Is BUILD_DATE stale without a prior `make clean`, for successive `make` calls?

### ISSUE THREAD

**Issue by xftroxgpx** [mitnk/cicada#7]
How do you ensure that the `BUILD_DATE` env var from here: https://github.com/mitnk/cicada/blob/340e8136465863c07832c9a19261c0b75b4034a5/src/build.rs#L15
is being updated upon each successful compilation, without having to manually `make clean` before `make` ?

If my understanding is correct(and I tested this a lil bit on my test project), `cargo` [caches the output](http://doc.crates.io/build-script.html#outputs-of-the-build-script) of `build.rs` and if you just `touch src/main.rs` for example, but not also `touch build.rs`, it will use the cached output and thus `BUILD_DATE`(and GIT_HASH for that matter) will be the stale one.

**Comment by mitnk** [comment]
I just tested on Mac with rustc 1.24.0-nightly - if I change (or just *touch*) main.rs and make, then the env `BUILD_DATE` changes on each `make`.

**Comment by xftroxgpx** [comment]
I can confirm the same! And I've also tested it on a new project and even a project within a workspace, both seem to update as expected! 

I must be hitting an edge case for my particular project and I wrongly assumed it happens for any project!

Apologies for wasting your time. I will edit this post if I figure out what was that edge case for my project.

Closing, as it's obviously not an issue for cicada!

**Comment by mitnk** [comment]
Never mind @xftroxgpx, we all learners :)

**Comment by xftroxgpx** [comment]
Thanks @mitnk !
Figured it out. 
It failed for me because I had this line in my `build.rs`

```rust
  println!("cargo:rerun-if-env-changed=A"); //if the environment variable's value changes the build script should be rerun.  
```

If I remove the line, it works as intended. Otherwise, sometimes, it just won't recompile `build.rs` after `src/main.rs` is touched.

Doc for that is here: http://doc.crates.io/build-script.html#outputs-of-the-build-script

Seems like a cargo bug, or I'm misunderstanding something here.

Simple test project [here](https://github.com/xftroxgpx/a3/tree/d0cfb65fc5908393af35b8f1e8f004775c6ef2db/system/Z575/OSes/3archlinux/on_baremetal/filesystem_now/archlinux/home/xftroxgpx/sandbox/rust/workspace_buildrs2/buildrs3)
My convoluted test project is [here](https://github.com/xftroxgpx/rustlearnage/commit/4154442ef202de50d8d4552a8e22f47f87551b14#diff-71a520a81fc5c0be0ecebccca95fd3d9)

PS: was using cargo 0.26.0 (git master) and rustc 1.24.0-dev (687d3d15b 2018-01-02), in this whole thread.
