### ISSUE TITLE
exit: entity not found

### ISSUE THREAD

**Issue by xftroxgpx** [mitnk/cicada#9]
Not expected:
```bash
$ echo 'echo 1;exit;echo 2'|./target/debug/cicada
1
exit: entity not found
2
```

Expected (in bash):
```bash
$ echo 'echo 1;exit;echo 2'|bash
1
```

This does work as expected though:
```bash
$ echo -e 'echo 1;exit;echo2' >a && chmod u+x a && ./target/debug/cicada ./a
1
```

**Comment by mitnk** [comment]
`exit` is too special.. but, yeah, this is a bug (minor one) I guess. I'll see If we could fix it. Thanks for reporting.

**Comment by mitnk** [comment]
This has been fixed on latest master. Please have a try.

**Comment by xftroxgpx** [comment]
Impressive extra work and response, thanks!
Tested working!
